controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    # joint_state_broadcaster:
    #   type: joint_state_broadcaster/JointStateBroadcaster

diffbot_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    # Values of prototype
    wheel_separation: 0.37
    wheel_radius: 0.06

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 1.0 # 0.5
    #publish_limited_velocity: true
    use_stamped_vel: true
    position_feedback: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

gpio_controller:
  ros__parameters:
    type: gpio_controllers/GpioCommandController
    gpios:
      - capture
      - unload
      - button
      - slope_up
      - slope_down
      - emergency
      - captured_duplos
    command_interfaces:
      capture:
        - interfaces:
          - active
      unload:
        - interfaces:
          - active
      button:
        - interfaces:
          - active
      slope_up:
        - interfaces:
          - active
      slope_down:
        - interfaces:
          - active
      emergency:
        - interfaces:
          - active
    state_interfaces:
      capture:
        - interfaces:
          - active
      unload:
        - interfaces:
          - active
      button:
        - interfaces:
          - active
      slope_up:
        - interfaces:
          - active
      slope_down:
        - interfaces:
          - active
      emergency:
        - interfaces:
          - active
      captured_duplos:
        - interfaces:
          - number
