scan_to_scan_filter_chain:
  ros__parameters:
    tf_message_filter_tolerance: 0.1
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: 0.0 # -20
        upper_angle: 3.14 # 160
        
        
