# Defines object locations as [x, y, theta]
drop_point: [0.5, 0.5, 0.78539816339]
zone4_outside_entry: [7.50, 4.48, 3.14]
zone4_inside_entry: [7.75, 6.53, 1.57]
zone4_inside_exit: [7.75, 6.53, 1.57]
zone4_outside_exit: [7.75, 6.53, 1.57]
zone3_inside_entry: [2.0, 7.50, 3.14]

zone5_start: [5.0, 7.0, 3.14]
zone6_start: [7.0, 4.0, 3.14]
zone4_start: [7.0, 7.0, 3.14]
button_robot_position: [7.0, 4.0, 3.14]
