<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.6221"/>
    <xacro:property name="chassis_width" value="0.408"/>
    <xacro:property name="chassis_height" value="0.2291"/>
    <xacro:property name="chassis_mass" value="1.0"/>

    <xacro:property name="wheel_radius" value="0.06"/>
    <!-- here 0.03 to not be in the chassis, normally it should be 0.06 -->
    <xacro:property name="wheel_thickness" value="0.03"/>
    <xacro:property name="wheel_mass" value="0.05"/>

    <xacro:property name="wheel_offset_x" value="0.0795"/>
    <xacro:property name="wheel_offset_y" value="0.202"/>
    <xacro:property name="wheel_offset_z" value="0.09855"/>

    <xacro:property name="small_wheel_offset_x" value="0.30105"/>
    <xacro:property name="small_wheel_offset_z" value="0.12955"/>

    <xacro:property name="small_wheel_radius" value="0.025"/>
    <xacro:property name="small_wheel_thickness" value="0.01"/>
    <xacro:property name="small_wheel_mass" value="0.04"/>


    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="green">
        <color rgba="0 1 0 1"/>
    </material>
    
    <!-- BASE LINK -->

    <link name="base_link" />

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint" />

    <!-- Burshes -->
    <joint name="brushes_joint" type="fixed">
        <parent link="base_link"/>
        <child link="brushes"/>
        <origin xyz="${0.20 + wheel_offset_x}  0 0" rpy="0 0 0"/>
    </joint>

    <link name="brushes" />
    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${wheel_offset_x} 0 ${chassis_height/2}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Red</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y + wheel_thickness/2} ${-wheel_offset_z}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Green</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y - wheel_thickness/2} ${-wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Green</material>
    </gazebo>

    <!-- LEFT FRONT WHEEL -->
    
    <joint name="left_front_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="left_front_wheel"/>
        <origin xyz="${small_wheel_offset_x} ${wheel_offset_y + small_wheel_thickness/2} ${-small_wheel_offset_z}" rpy="${-pi/2} 0 0" />
        <!-- <axis xyz="0 0 1"/> -->
    </joint>

    <link name="left_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${small_wheel_radius}" length="${small_wheel_thickness}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${small_wheel_radius}" length="${small_wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${small_wheel_mass}" length="${small_wheel_thickness}" radius="${small_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_front_wheel">
        <material>Gazebo/Green</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- RIGHT FRONT WHEEL -->

    <joint name="right_front_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="right_front_wheel"/>
        <origin xyz="${small_wheel_offset_x} ${-wheel_offset_y - small_wheel_thickness/2} ${-small_wheel_offset_z}" rpy="${pi/2} 0 0" />
        <!-- <axis xyz="0 0 -1"/> -->
    </joint>

    <link name="right_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${small_wheel_radius}" length="${small_wheel_thickness}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${small_wheel_radius}" length="${small_wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${small_wheel_mass}" length="${small_wheel_thickness}" radius="${small_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

     <gazebo reference="right_front_wheel">
        <material>Gazebo/Green</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>